version: '3.8'

services:
  tasksdb:
    image: mongo
    container_name: tasksdb
    restart: always
    ports:
      - 27017:27017
    version: '3.8'

services:
  tasksdb:
    image: mongo
    container_name: tasksdb
    restart: always
    ports:
      - 27017:27017
    